### ISSUE TITLE
dashDB examples fail on Basic clusters due to missing db2jcc*.jar files

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#17]
```
==> default: Test failed  ./examples/DashDBPullWithSpark
==> default: Test failed  ./examples/DashDBPushWithSpark
```

On a Standard cluster libs are downloaded from the following locations on master-2:

```
                get from: "/usr/ibmpacks/bigsql/4.1/db2/java/db2jcc.jar",
                    into: "${projectDir}/lib/db2jcc.jar"

                get from: "/usr/ibmpacks/bigsql/4.1/db2/java/db2jcc4.jar",
                    into: "${projectDir}/lib/db2jcc4.jar"

                get from: "/usr/ibmpacks/bigsql/4.1/db2/java/db2jcc_license_cu.jar",
                    into: "${projectDir}/lib/db2jcc_license_cu.jar"
```

These files don't exist on Paygo

**Comment by pregazzoni** [comment]
Chris. Does Paygo have bigsql service installed?

**Comment by snowch** [comment]
I don't think it does.  I'll send you my connection.properties offline if you want to take a look.

**Comment by snowch** [comment]
workaround code:
- https://github.com/snowch/biginsight-examples/commit/c677cf01d498b7e88220e5f0cbee0a2ea9b1645e
- https://github.com/snowch/biginsight-examples/commit/24602e36b333b4f200be0c1be50e70c239c3e099

the workaround is manual, you need to copy jar files to ./download folder.
