### ISSUE TITLE
Query a cluster to determine its services?

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#21]
At the moment, a test is run even if the cluster doesn't have the service enabled.  An example of this is running BigX tests on a Basic (paygo) cluster.  It would be much nicer if we could skip a test if that cluster doesn't support that test.

Is there some metadata we can query on the cluster to:
- the type of cluster, basic or standard
- detect which services are available

**Comment by pregazzoni** [comment]
I think for this, could query ambari rest api to see if service is present e.g

https://<ambari>:<port>/api/v1/clusters/<clustername>/services

Then check json object to see if service is there or not.

**Comment by snowch** [comment]
Thanks @pregazzoni

**Comment by pregazzoni** [comment]
See new ambari example I added. It lists all services on given cluster.
