### ISSUE TITLE
Ambari example to restart a service

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#46]
It would be good if we could restart a service from the command line, e.g.

```
../../gradlew RestartService -Pservice=BIGSQL
```

See also: https://github.com/snowch/biginsight-examples/issues/39

**Comment by pregazzoni** [comment]
Yes will create that example

**Comment by snowch** [comment]
Great - thanks @pregazzoni

**Comment by pregazzoni** [comment]
see commit 847cc35
