### ISSUE TITLE
`gradlew test` to have more detailed output

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#47]
At the moment `gradlew test` doesn't inform you how may tests are being run per example.  Ideally, `gradlew test` should show more detailed output, e.g.

```
:baseTest
Running base tests
Test passed  ./examples/WebHdfsGroovy:Put
Test passed  ./examples/WebHdfsGroovy:Mkdir
Test passed  ./examples/WebHdfsGroovy:Ls
Test passed  ./examples/WebHdfsCurl:Mkdir
Test passed  ./examples/WebHdfsCurl:Ls
Test passed  ./examples/WebHdfsCurl:Put
...
```

@pregazzoni - what are your thoughts on this?

**Comment by pregazzoni** [comment]
Maybe could leverage a standard test framework like junit or also [Spock](http://spockframework.github.io/spock/docs/1.0/index.html) looks interesting. Need to do more reading on it. See also http://www.petrikainulainen.net/programming/testing/writing-unit-tests-with-spock-framework-creating-a-gradle-project/

**Comment by snowch** [comment]
Spock would be awesome.  In the meantime, I've committed the framework for this change.

**Comment by snowch** [comment]
Previous behavoir with summary level output can be run with:

```
./gradlew test -PsummaryOutput
```
