### ISSUE TITLE
Is it possible to extend ServiceCheck to TEXTANALYTICS and BIGSQL, BIG..?

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#59]
```
Exception in thread "main" java.lang.AssertionError: Make sure to provide correct SERVICE name. Valid values are HDFS, YARN, MAPREDUCE2, HIVE, PIG, OOZIE, ZOOKEEPER. Expression: (service_check != null). Values: service_check = null
```

I'm not sure if it is possible, but it would be great to be able to run service check on the value add components.

**Comment by pregazzoni** [comment]
Chris, I can add that for BIGR, BIGSQL. for TA and SHEETS we might not have service check for now. Will need to check with dev what is plan or thoughts on that.

**Comment by snowch** [comment]
Thanks Pierre!

**Comment by pregazzoni** [comment]
Added BIGR/BIGSQL via [Add check for BIGSQL and BIGR](https://github.com/snowch/biginsight-examples/commit/ee5358491d92e5fb721c91479b29794ffea6772b)

**Comment by pregazzoni** [comment]
BTW check for other value-adds:
1. TA should be in 4.2
2. SHEETS not clear yet.

Closing this task for now.
