### ISSUE TITLE
Add simple jsqsh (non-interactive) example

### ISSUE THREAD

**Issue by pregazzoni** [snowch/biginsight-examples#62]
For example, create task to do following:

```
$ ./jsqsh-2.2/bin/jsqsh biginsights -C config/ -e -i foo.sql 

select * from (values (1));
+---+
| 1 |
+---+
| 1 |
+---+
1 row in results(first row: 0.105s; total: 0.183s)
```

**Comment by snowch** [comment]
@pregazzoni, I did a sneaky commit that runs jsqsh from gradle.  I think using gradle is ok to download jsqsh and create the config but probably not to run the jsqsh command. This will support your workflow above.  What do you think?

**Comment by snowch** [comment]
I.e.

I'm not 100% sure how robust the Exec task is for running jsqsh.  I think running it directly will be much better.  I'll change the build.gradle to support the manual workflow:

```
task('RunJsqsh', type:Exec) {

    dependsOn SetupJsqsh

    commandLine "${projectDir}/jsqsh-2.2/bin/jsqsh","-C","${projectDir}/config/"
    standardInput = System.in
}

task('SetupJsqsh', type:Exec) {
    dependsOn DownloadJsqsh, CreateConfig
}
```

**Comment by snowch** [comment]
Thanks for fixing to use BIGSQL_HEAD.

Tidied up task names with: https://github.com/snowch/biginsight-examples/commit/f09b70aed065ce57416a98ad511c1cdd10328826

**Comment by pregazzoni** [comment]
I think interactive is fine. Will add some info to README.

What about generating config for HIVE as well?

**Comment by snowch** [comment]
Sounds like a good idea.  Maybe the approach with jsqsh could be used and replace the existing mechanism here: https://github.com/snowch/biginsight-examples/tree/master/examples/HiveBeeline?

**Comment by pregazzoni** [comment]
Still like having example with beeline. Closing this for now. The jsqshsetup task shows how interactive example works.
