### ISSUE TITLE
Big SQL example to create CSV file

### ISSUE THREAD

**Issue by pregazzoni** [snowch/biginsight-examples#67]
Basic example to select some data from existing table, write it to HDFS as CSV (comma).

**Comment by snowch** [comment]
Nice one.  Thanks Pierre.

Should we rename QueryHdfs to something like CreateExternal?

**Comment by pregazzoni** [comment]
Yes I think so. Let me do that today.

Also was debating about keeping or removing the TABLE.csv at the end of the example. thoughts?
