### ISSUE TITLE
Check BigInsights Home

### ISSUE THREAD

**Issue by pregazzoni** [snowch/biginsight-examples#69]
Simple Geb/Selenium example which checks:
1. can access BI Home
2. contains 3 sections for Sheets, TA and DSM

**Comment by snowch** [comment]
Nice Pierre - thanks!

I tried to extend the example to use PhantomJS based on an [example](https://github.com/geb/geb-example-gradle) that downloads phantomJS for you and runs it headless.   At the moment the code is broken so I've kept it in a separate script, CheckHomePhantomJS.   The issue for this is here: https://github.com/snowch/biginsight-examples/issues/70

**Comment by snowch** [comment]
One other option may be to try the approach here: https://github.com/founddrama/phantomjs-cookbook/blob/master/chapter05/recipe01/src/test/java/phantomjs/cookbook/RemoteWebDriverTest.java although that will require firing up phantomjs first with something like: `phantomjs --webdriver=4444`

**Comment by pregazzoni** [comment]
I guess we can close this task and open additional task for extending coverage.

The headless example using PhantomJS is now default but we can keep the FF example for reference unless you think it should be removed.

**Comment by snowch** [comment]
I think it would be good to keep the FF version as it is easier to see what is happening when things go wrong.

**Comment by pregazzoni** [comment]
Sounds good.
