### ISSUE TITLE
Biginsights Home test with PhantomJS is broken

### ISSUE THREAD

**Issue by snowch** [snowch/biginsight-examples#70]
https://github.com/snowch/biginsight-examples/blob/master/examples/BiginsightsHome/CheckHomePhantomJS.groovy is currently broken:

```
Exception in thread "main" Assertion failed:

assert title == "IBM BigInsights"
       |     |
       ""    false
```

**Comment by pregazzoni** [comment]
so looked into this one and seems like need to deal with SSL ... which was tricky but got it working. now I failed on big sheets not being enable on my instance but that is expected:

```
Opening BIHOME
https://***MASKED***/gateway/default/BigInsightsWeb/#/welcome
Check BigSheets
Check for Text Analytics
Check for Data Server Manager for Big SQL
Check there are no unavailable service
Exception in thread "main" Assertion failed: 

assert $("div", class: "header").has(".ng-scope").size() == 0
       |                         |                |      |
       |                         |                1      false
       |                         [[[[[PhantomJSDriver: phantomjs on MAC (bac742a0-19fd-11e6-89e0-551c634fb677)] -> tag name: html]] -> css selector: div.header]]
```

**Comment by pregazzoni** [comment]
Fix via commit 821de59

**Comment by snowch** [comment]
Awesome Pierre - thank you!  

I've added Travis automated testing to the project.  Click the icon on the README.md to see the build status.

We can test BiginsightsHome headless now, so I've added that: https://github.com/snowch/biginsight-examples/commit/fb60c4fd318c5080a138f887cf9b162faf9bd586

**Comment by pregazzoni** [comment]
Yeah saw you added travis which is nice.

**Comment by snowch** [comment]
Although the build is broken trying to install r-base from rstudio's cran.  Hopefully it is just an upstream issue and will sort itself out soon.  Just tested on vagrant and that is broken too, suggesting that the problem is upstream.

**Comment by snowch** [comment]
I disabled the rstudio version of R, ran the tests and CheckHomePhantomJS failed.  It was because my text analytics was down, so I restarted it and now CheckHomePhantomJS succeeds.

This test is awesome!  I've contacted travis support to see if I can get this test running on a [cron](https://docs.travis-ci.com/user/cron-jobs/) to measure the uptime of the Biginsight home services.

**Comment by pregazzoni** [comment]
Cool. Will have to think/discuss if we want to extend it.
