### ISSUE TITLE
Issue with Hive beeline test

### ISSUE THREAD

**Issue by cyborg7** [snowch/biginsight-examples#85]
terminal crashes ... note that the Hive connection shows "closed"

---
## Output from test

$ ./gradlew.bat -p examples/HiveBeeline -q Example
[ant:exec] Result: 1
Connecting to jdbc:hive2://bi-hadoop-prod-4006.bi.services.us-south.bluemix.net:10000/default;ssl=true;sslTrustStore=C:\Big_Data\BigInsights\GitSamples\biginsight-examples\examples\HiveBeeline/truststore.jks;
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/IBM_ADMIN/.gradle/caches/modules-2/files-2.1/org.apache.logging.log4j/log4j-slf4j-impl/2.4.1/1153bec315f388b2635c25cf97105ae9dce61b58/log4j-slf4j-impl-2.4.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/IBM_ADMIN/.gradle/caches/modules-2/files-2.1/ch.qos.logback/logback-classic/1.0.9/258c3d8f956e7c8723f13fdea6b81e3d74201f68/logback-classic-1.0.9.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/Users/IBM_ADMIN/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.5/6edffc576ce104ec769d954618764f39f0f0f10d/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.apache.logging.slf4j.Log4jLoggerFactory]
ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console.
Illegal character in path at index 57: hive2://dummyhost:00000/default;ssl=true;sslTrustStore=C:\Big_Data\BigInsights\GitSamples\biginsight-examples\examples\HiveBeeline/truststore.jks;
Beeline version 2.0.0 by Apache Hive
0: jdbc:hive2://bi-hadoop-prod-4006.bi.servic **(closed)**>

**Comment by snowch** [comment]
See also https://github.com/snowch/biginsight-examples/issues/91

Hopefully fixed - please test @cyborg7
